groups:
  - id: service
    prefix: service
    type: resource
    brief: >
      A service instance.
    attributes:
      - ref: service.name
        requirement_level: required
        stability: stable
      - ref: service.version
        stability: stable